### ISSUE TITLE
versioning of Android APK

### ISSUE THREAD

**Issue by IzzySoft** [thevindu-w/clip_share_server#1]
The APK file attached to the latest release still identifies with `versioncode: 1`. As Android uses `versionCode` to tell versions apart and decide whether an APK is an update to the installed app, this should always be increased before making a release.

That said: seems like I missed it, but is the source for the Android app contained in this repo?

**Comment by thevindu-w** [comment]
Currently, the source of android apk is not in a public repo. I have it in my private repo. I may release the source of the android client in the future.

**Comment by thevindu-w** [comment]
Update: Fixed the issue by updating the `versioncode` to `2`. I updated the file in release `v2.0`. Please get the new apk file from there.

**Comment by IzzySoft** [comment]
Thanks! But I'm afraid I'll have to wait for its source code to be published under a FLOSS license. Idea was to include the app with [my repo]([https://apt.izzysoft.de/fdroid) to make it easier discoverable and available to end-users :wink:

**Comment by thevindu-w** [comment]
Probably I'll publish it under MIT or a similar license (I haven't decided yet). But I have to make some changes before publishing it. I'll try to do it as soon as possible.

**Comment by IzzySoft** [comment]
No pressure – I'm ready when you are, just give me a ping then please. Thanks a lot!

**Comment by thevindu-w** [comment]
@IzzySoft the source of the Android client is now available at [github.com/thevindu-w/clip_share_client](https://github.com/thevindu-w/clip_share_client).

**Comment by IzzySoft** [comment]
Thanks! Let's see how the mix works (with APKs in a different repo than the code). Adding your app now to my repo, should [show up here](https://apt.izzysoft.de/packages/com.tw.clipshare/) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from e.g. your readme then. And should you have some screenshots to add, let me know.

Oh, you could also set up Fastlane structures in the client repo (feel free to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance), then your changes to description or graphics would simply be pulled along with new versions (updates run once per day).

If you have any questions, don't hesitate asking. Else I guess: all done, and this issue can be closed?

**Comment by IzzySoft** [comment]
> Since you are developing Android apps

I do? That's news to me :see_no_evil: Nope, I'm not an Android dev, sorry. So no, I can't.

> Screenshots of the Android app's UI?

Yupp. To show along with your app's listing, see the link from my previous comment: It's [live here now](https://apt.izzysoft.de/packages/com.tw.clipshare/).

**Comment by thevindu-w** [comment]
> Oh, you could also set up Fastlane structures in the client repo (feel free to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance), then your changes to description or graphics would simply be pulled along with new versions (updates run once per day).

I added Fastlane with screenshots. Please check that. If there is no issues with that, we can close this.

**Comment by IzzySoft** [comment]
First apologies for my delayed answer, I'm currently quite busy with a big task at F-Droid.org…

Fastlane looks fine so far: I've configured it on my end and triggered a manual pull, so with the next sync screenshots should show up in my repo. Just the full description I skipped for now; may I recommend some minor adjustments there?

First, no need for the "header" – the app name is always displayed along anyway. For the remaining part, you can use simple HTML (or should at least keep an empty line between the paragraphs, so it can be processed as Markdown). HTML variant I'd recommend would look like this:

```html
<p>Share the clipboard between your phone and desktop. Share files and screenshots securely. This is a lightweight, cross-platform app to share copied text, files, and screenshots between an Android phone and a desktop.</p>
<p>This is the Android client of ClipShare. You will need the server on your desktop to connect with it. The ClipShare server is simple and lightweight. Simply run the server on your Windows or Linux machine to use the ClipShare app. You can find the server <a href='https://github.com/thevindu-w/clip_share_server'>here at Github</a>.</p>
```

If you want to have your app at F-Droid.org one day, I'd even suggest putting all that in a single line (they replace each `\n` by a `<br>`, so better give them none of that :see_no_evil:).

**Comment by thevindu-w** [comment]
> First, no need for the "header" – the app name is always displayed along anyway. For the remaining part, you can use simple HTML (or should at least keep an empty line between the paragraphs, so it can be processed as Markdown). HTML variant I'd recommend would look like this:
> 
> ```
> <p>Share the clipboard between your phone and desktop. Share files and screenshots securely. This is a lightweight, cross-platform app to share copied text, files, and screenshots between an Android phone and a desktop.</p>
> <p>This is the Android client of ClipShare. You will need the server on your desktop to connect with it. The ClipShare server is simple and lightweight. Simply run the server on your Windows or Linux machine to use the ClipShare app. You can find the server <a href='https://github.com/thevindu-w/clip_share_server'>here at Github</a>.</p>
> ```
> 
> If you want to have your app at F-Droid.org one day, I'd even suggest putting all that in a single line (they replace each `\n` by a `<br>`, so better give them none of that see_no_evil).

Thanks for your suggestions. I updated the full description with HTML.

**Comment by IzzySoft** [comment]
Thanks a lot! Enabled that as well then. So all open points are solved now. Seems like my updater at least can deal fine with your fastlane now, let's see how the update check itself works:

```
$ iod repo get com.tw.clipshare
com.tw.clipshare: looking for 'https://api.github.com/repos/thevindu-w/clip_share_server/releases'
com.tw.clipshare: checking tag 'v2.0'
com.tw.clipshare: lastRelNo set to 'v2.0', checking for files
com.tw.clipshare: Upstream file date (2023-07-26 10:30) not newer than ours (2023-08-03 00:05), skipping.
com.tw.clipshare: returning local appdata as ['2.4.2','',0]
com.tw.clipshare: 2.4.2 up-to-date.
```

Yupp, despite the "other repo used" and "tag name not corresponding to versionName", it seems to handle it fine. So all set: Thanks for your help! Time to close the issue then. Should you have any questions (now or in the future), don't hesitate to reach out to me :smiley:

**Comment by thevindu-w** [comment]
@IzzySoft In [Fdroid](https://apt.izzysoft.de/fdroid/index/apk/com.tw.clipshare/), the `Source` and the `ChangeLog` of the app is set to the [server repo](https://github.com/thevindu-w/clip_share_server) instead of the [client repo](https://github.com/thevindu-w/clip_share_client). Is that a mistake?

**Comment by IzzySoft** [comment]
I have to set `Source` to the server repo, or my updater would not work (it uses the `Source` URL). Be welcome to file an issue with my tracker at https://gitlab.com/IzzyOnDroid/repo/ – an idea would be to move that to `RepoURL`, as F-Droid.org does it. Won't be implemented over night, though, as I'd need to carefully check for all references/dependencies. But should be done, maybe.

`Changelog` I could adjust. Is there a changelog I shall point to?

**Comment by thevindu-w** [comment]
> I have to set `Source` to the server repo, or my updater would not work (it uses the `Source` URL)

But the client app and its source are independent of the server. It's better if you can get the source from the client repo as the server repo does not contain anything about the client (except the apk file in releases). Also, the Fastlane is set up in the client repo. If it fails because there are no releases in the client repo, I can create a release there.

> `Changelog` I could adjust. Is there a changelog I shall point to?

Currently there's no ChangeLog. May be I'll add it for later versions.

**Comment by IzzySoft** [comment]
> But the client app and its source are independent of the server.

Of course it is. If you'd make releases in the client repo and attach the APK there, I gladly adjust that at my end!

> It's better if you can get the source from the client repo

You're speaking F-Droid.org here, which builds from source. I do not build, I depend on the APK you provide. And that's not available at the client repo :man_shrugging:

> Also, the Fastlane is set up in the client repo

Yes, and my updater fetches it from there. Again a difference to F-Droid.org: I can configure custom locations for that.

> I can create a release there.

Now, **that** would eneable me to immediately "clean up the link mess" on my end indeed :smiley: Please let me know should you have established that, as currently my updater would look here for new releases with APKs attached.

> Currently there's no ChangeLog. May be I'll add it for later versions.

If there's no explicit `changelog.md` or the like, but the release have corresponding release notes (which is the case with about 90% of the apps in my repo), I'd simply point there.

**Comment by thevindu-w** [comment]
> Now, **that** would eneable me to immediately "clean up the link mess" on my end indeed smiley Please let me know should you have established that, as currently my updater would look here for new releases with APKs attached.

Done 👍. Release is available [here](https://github.com/thevindu-w/clip_share_client/releases/v2.5.0).

> If there's no explicit `changelog.md` or the like, but the release have corresponding release notes (which is the case with about 90% of the apps in my repo), I'd simply point there.

I'll add ChangeLogs in fastlane/metadata/android/en-US/changelogs/.

**Comment by IzzySoft** [comment]
Thanks! Updated my config, fetched the next update (v2.5.0) fine. Changelogs were not yet present; I've enabled them on my end already, though, so as soon as they are there they will be fetched with the next release then. Thanks a lot!
