### ISSUE TITLE
I think there should be an option to select where to send files on PC

### ISSUE THREAD

**Issue by JFMugen** [thevindu-w/clip_share_server#11]
Even if it manually, like creating a .ini file near exe.

**Comment by thevindu-w** [comment]
There is the working_dir configuration option to specify where the files should be saved. You can find how to do this in the Configuration section of the README.

**Comment by JFMugen** [comment]
> There is the working_dir configuration option to specify where the files should be saved. You can find how to do this in the Configuration section of the README.

Hmm, my bad I didn't check before :/ 

But I can't use it, gives an error. Isn't that right? 

**working_dir=.C:\Users\(username)\Downloads**

**Comment by JFMugen** [comment]
> Is there a dot before C:\ ? It should not have a dot before C: It should be like `working_dir=C:\something`

I thought there should be a .dot because of your example code haha :D Now I remembered .dot supposed to mean "here" right?

**Comment by thevindu-w** [comment]
> .dot supposed to mean "here" right?

Yes, relative to current working directory. C:\Users\something is an absolute path. The `working_dir` can be specified with either relative or absolute path.
