### ISSUE TITLE
Sharing Remote Desk ‏‪1 876 365 234‬‏

### ISSUE THREAD

**Issue by Salm3** [thevindu-w/clip_share_server#14]
Hello there,

I would like to share a contact of my AnyDesk Address Book with you (1 876 365 234). 

AnyDesk is an easy to use Remote Desktop application and works without installation. You can download AnyDesk from:

https://anydesk.com/

Best

**Comment by thevindu-w** [comment]
Okay, is there any specific issue or suggestion?
